### ISSUE TITLE
SPIKE: Add authentication to ecr viewer (for local dev)

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#1267]
## Action Requested
Spike on how to add API key authentication to the eCR viewer.

## Acceptance Criteria
Only authenticated requests are allowed through `/view-data` - all unauthenticated requests are denied.

(This only applies to local development for now; working with API keys in the cloud will require a bit more work)

## Testing
Our integration test suite may need to be updated.

## Background & Context
The plan for NBS integration is to give NBS an API key for the ecr-viewer. They'll pass that API key along with every request they make to our services, and we'll only authenticate requests made through NBS. 

## Additional Information
There are a lot of unknowns with this architecture! Should the API key be passed in as a parameter to the service directly? How will we generate it? Should we use a 3rd party auth provider to do so? 

It looks like the most basic way to do this would be to generate an API key, store it in a `.env` file, gitignore that .env file, and only authenticate if requests pass in the key directly. But we should check to ensure this is actually best practice from a security perspective.

**Comment by emmastephenson** [comment]
The outcome of this spike should be further tickets written to implement the chosen authentication solution.

**Comment by BobanL** [comment]
We got sign off from NBS that they can store a private key and can create a JWT token. 
![image](https://github.com/CDCgov/phdi/assets/10108172/aff0798d-5b46-4399-b403-27dc0d7d8500)
Since there is only one relationship here between the sites an [asymmetric JWT](https://medium.com/@swayamraina/symmetric-vs-asymmetric-jwts-bd5d1a9567f6#:~:text=Asymmetric%20signing%20of%20JWTs) will be sufficient in securing the connection.

The work will be split into three tickets. 
1. #1354 - Save backend auth as cookie
2. #1355 - Remove auth from url
3. #1356 - Validate token on incoming requests to /api/*
