### ISSUE TITLE
SPIKE: Understand eCR Rhapsody Route requirements

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#1533]

**Comment by robertmitchellv** [comment]
## eICR XML ➡️ NBS

eICR messages come from AIMS ➡️ networked storage and can be written to a staging table for further processing by two methods:
1. a Rhapsody route; or,
2. a batch process (unclear what the compute for this batch process is at the moment).

The staging table is called `NBS_MSGOUTE.dbo.NBS_INTERFACE`:

| Field                  | Description                                                        |
|------------------------|--------------------------------------------------------------------|
| `NBS_INTERFACE_UID`      | Auto generated                                                     |
| `PAYLOAD`                | `NULL`                                                               |
| `IMP_EXP_IND_CD`         | `I`                                                                  |
| `RECORD_STATUS_CD`       | `ORIG_QUEUED`                                                        |
| `RECORD_STATUS_TIME`     | System generated                                                    |
| `ADD_TIME`               | System generated                                                    |
| `SYSTEM_NM`              | Derived from the document                                           |
| `DOC_TYPE_CD`            | `PHC236`                                                             |
| `ORIGINAL_PAYLOAD`       | Imported eICR XML picked from STEP 1                                |
| `ORIGINAL_DOC_TYPE_CD`   | Derived from the document. By default it is `2.16.840.1.113883.10.20.15.2^2016-12-01` |

This staging table acts almost as an API request in an abstract sense; where there are metadata fields that are fed to subsequent processes that determine how the payload is run--just that it is done via SQL rather than REST.

Next the `PHCRImporter.bat` file is run:
* This process will read the eICR messages from the `NBS_MSGOUTE.dbo.NBS_INTERFACE` staging table's `ORIGINAL_PAYLOAD` column (which is the full eICR message) and do some data parsing (currently we do not have any visibility into this parsing). It then writes to the `MSG_XML_MAPPING` table:

| `MSG_XML_MAPPING`                  |
|------------------------|
| `MSG_ANSWER`             |
| `MSG_CASE_INVESTIGATION` |
| `MSG_CONTAINER`          |
| `MSG_INTERVIEW`          |
| `MSG_ORGANIZATION`       |
| `MSG_PATIENT`            |
| `MSG_PLACE`              |
| `MSG_PROVIDER`           |
| `MSG_TREATMENT`          |

Then the Rhapsody route `INV_PHDC_CDA_Export_SQL.rlc` is run:
* This is the Rhapsody route that takes the data from the `MSG_XML_MAPPING` table above and then writes PHDC.

Interestingly the `PHCRImporter.bat` file is run again, but this time it reads PHDC written by the Rhapsody route, which creates a document in the `NBS_ODSE.dbo.NBS_Document` table.

To definitively answer some of our questions around what is the minimum amount of fields required in an eICR for these processes to still function correctly as well as whether or not _any_ of the processes enforce any kind of XML validation we'll likely need the following files:
* `PHCRImporter.bat`
* `INV_PHDC_CDA_Export_SQL.rlc`

## What we can intuit from available information 🤔 💭 

Reviewing SME presentations to STLTs from NBS Central there were some details that we can reasonably interpret to help us begin planning a proof on concept process for a config driven eCR compactor of sorts (name still a WIP) to allow a user to select pieces of the eICR message they care the most about that presents more focused eICR data relevant to the STLT.

Since NBS has worked on eICR before the introduction of the Reportability Response (RR), effectively they have two mechanisms to get eICR data into NBS. The preference is to use the process that leverages diagnosis code from the accompanying RR but it is still possible to send a single eICR message. The other detail is that the import process will also work for C-CDA in addition to eICR. Since both eICR and PHDC are derivatives of C-CDA, I reason that so long as a post-processed eICR is valid C-CDA we should still be able to ingest the focused/compacted eICR messages into NBS. It is still possible, however, that the C-CDA import really only works without an RR, which is why reviewing the above document should help answer lingering questions.

The other detail wroth considering is how we decide to implement terminology mapping, and whether or not we rely on the Rhapsody look up tables, e.g., the `code_to_condition` table. For the moment this feels like a later spike worth investigating after a proof of concept is put together.

**Comment by robertmitchellv** [comment]
@DanPaseltiner let me know how you feel about ⬆️
