### ISSUE TITLE
Deploy the DIBBs demo stack to AWS - OTEL

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#1568]
GIVEN that the DIBBs demo stack is fully configured and tested,
WHEN the decision is made to deploy this stack to the cloud,
THEN the stack, including all necessary services and components, should be successfully deployed and operational in the chosen cloud environment.

**Comment by robertandremitchell** [comment]
Based on feedback, prioritizing the setup of opentelemetry to terraform.

The metrics we are now exposing via the pod on the cluster should be sufficient for our other services. It should also be sufficient for

spinning up an otel-collector pod,
allowing a user to plug in (Prometheus, Cloudwatch, etc), and
scrape from the pod.
Prometheus and Jaeger should be able to get what they need without us having to expose any of those metrics via an endpoint. I have left the /metrics endpoint there in the event there is a reason we would want to expose the otel-collector metrics for demonstration purposes.

Because of the uniqueness of AWS' cloud ecosystem, compared to Azure, they do not strip/clean the endpoint names for things like otel-collector, prometheus, etc. This makes it difficult with our current setup to be able to use out-of-the-box. It’s the same issue that led the team to add the middleware to the BaseService - AWS app gateway can’t strip off the path it uses to route requests to different services. Communication between services should be working just fine, but in order to enable access from the outside via dibbs.cloud, we’ll need a reverse proxy like nginx.

The solution would be to set up nginx as a reverse proxy, but this would be for the benefit of making our internal implementation of prom/graf/jaeger work properly. However, as noted above, the work on this PR should be sufficient for otel, as we don't need to expose an otel endpoint.
