### ISSUE TITLE
SPIKE: How can we make the the coarse grained filter condition specific

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#1824]
We received feedback from ID that which sections of the eCR body they would like to retain likely depend on the condition. They requested that the sections retained by the coarse grained filter could be defined by condition. Let's consider how we could store this kind of configuration and allow users to create/update via API as needed.

**Comment by bamader** [comment]
Slightly confused on what this change is actually asking for. The coarse grained filter (or what we might soon rename the section filter) currently works by accepting a list of sections to include in the refined eCR message. Is the ask here to change the signature to instead accept a single condition (it would have to be one since we can't preserve different sections for different conditions and still make a valid XML message) and then based on that condition, filter sections accordingly? If so:

- what's to stop the user from just using their own heuristics to say "well, if my condition is COVID, I know I want sections A, B, and C, so I'll ask the endpoint for those three"?
- are we hoping to build up some kind of mapping or dictionary in the program that knows "for X condition, give me Y sections"? 

Alternatively, are we thinking of changing the actual logic of the filter to only retain the sections in which the condition occurs? For example, instead of the user supplying the sections they want, they supply a single condition and we preserve only the parts of the XML with data relating to that condition? If that's the case, how is this different from the fine-grained filter (alternatively renamed condition filter)?
