### ISSUE TITLE
SPIKE: How can we visualize eCRs for end user feedback?

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#1915]
Use the the eCR Viewer? Use APHL XSLT transforms? Something else?

**Comment by m-goggins** [comment]
WIP


### Lowest Lift: [XLCompare](https://xlcompare.com/compare-xml-files.html ) 

Pros: 
- Free and easy to download; no dev time
- Works for XML

Cons:
- Not automatic, e.g., user would need to manually pull up two files for comparison (potentially fine for proof of concept)
- Compares line by line (rather than by node) so the user has to put in a little work to truly compare
- Requires download, which could be 

### eCR Viewer
Pros:
- Could be automated 
- Looks nicer than XLCompare
Cons:
- Would take a good amount of dev time to get the eCR viewer
