### ISSUE TITLE
LAC Writeup

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#193]
### Why are we doing this?
To understand if our record linkage algorithm will be useful to LAC, we need to provide them with a comparison of their existing algorithm's performance vs our own algorithm's performance.

### Action Requested
Compare the results of the LAC record linkage algorithm with our own record linkage algorithm.

### Acceptance Criteria
A write-up is developed to highlight points of comparison and shared with LAC.

**Comment by emmastephenson** [comment]
Marcelle and Brandon:
Wanted to create a shareout that documents everything that's been done so far, what we learned along the way, and where we want to go in the future. One stop shop. Goal - get LAC's feedback on how to proceed.
Potential demo for Friday - talking through the writeup and algorithm comparison.

**Comment by emmastephenson** [comment]
@bamader to capture the three options for next steps in this ticket.

**Comment by bamader** [comment]
Paths to continue developing that we want to solicit feedback on:
1. adding probabilistic corrections to the algorithm to supplement the deterministic logic; this consists of a few additional functions that are widely considered the industry standard to add; they are likely to improve accuracy substantially and shouldn't take too long, but will defer starter kit integration
2. adding nickname resolution; when profiling the types of misses the linkage algorithm makes most frequently, patients whose names are swapped for nicknames are the top culprit, so this would involve blocking on name sets that include nicknames rather than just names; would likely require creative design and longer time; potentially the lowest priority
3. moving to integration with the starter kit; this option would see us call the algorithm we've developed so far a done, completed MVP, and would focus instead on investing time and resources into spinning up the infrastructure necessary to fully integrate linkage with the SDK; there will likely need to be conversations had around this so it may be possible to do 1 and 3 simultaneously, but this *will* have to happen by the end of the contract

**Comment by emmastephenson** [comment]
Demo'd on 3/3/23
