### ISSUE TITLE
Make helm charts use the latest version of each service's image in `values.yaml`

### ISSUE THREAD

**Issue by bamader** [CDCgov/phdi#1932]

**Comment by robertandremitchell** [comment]
So there were a few things I was reading up on. 

First, some of the read I found made it seem like bad practice to go into phdi-charts and set them all to latest. I think the line of thinking is that services that call upon each other could end up calling on different versions (i.e., orchestration v1.4.1 calling message-parser v1.4.0). I don't think that's really a concern for our work, given that the way we cut releases ensures all of our services are on the same version. 

It also doesn't seem to be prohibitive: https://medium.com/@michael.vittrup.larsen/why-we-should-use-latest-tag-on-container-images-fc0266877ab5. 

So in theory, we _should_ be fine just calling them all `latest`. However, I do think this may already be accounted for in the code with this section: https://github.com/CDCgov/phdi-playground/blob/main/terraform/aws/implementation/modules/eks/main.tf#L288-L294.

If I understand it correctly, this is grabbing the latest version and updating it dynamically so that we shouldn't technically need to update the version of the code each time.

When I look at the terraform deploy, it does in fact seem to be updating the chart versions appropriately: https://github.com/CDCgov/phdi-playground/actions/runs/9389080551/job/25855790920#step:9:484. In this section, we see fhir-converter updating from 1.4.2 to 1.4.4 despite the original chart being on 1.2.1: https://github.com/CDCgov/phdi-charts/blob/main/charts/fhir-converter/values.yaml. 


@bamader , curious your thoughts if that makes sense? My next step was to raise in the dev channel to see if that was a correct read. If we can confirm, we may be able to close without further update, except perhaps to note this more explicitly in both `phdi-charts` and `phdi-playground`.

**Comment by bamader** [comment]
This is absolutely madladness. I agree with your reading of both the best practice and the linked version updating; it just blows my mind that we wouldn't make that more explicit somewhere. If that's true, can we do away with the version param in each of the charts' `values.yaml` files entirely? That might make any explanation we add to the chart repo's readme about terraform handling versioning a little bit cleaner and more explicit. But even if we can't delete that param, I definitely think we should update some documentation to make this cleaner.

**Comment by robertandremitchell** [comment]
Gonna make a quick `description.md` this morning for both repos, then can close out.
