### ISSUE TITLE
Set up a virtual network to contain Azure resources

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#204]
### Why are we doing this?
Azure resources within the LAC project have some endpoints that are technically open to the public. There's no risk of PII leaks with these endpoints, but they should not be publicly accessible.

### Action Requested
Add a virtual network/subnet to contain the Azure resources that are created in the quick start pipeline, and ensure LAC's Azure resources are behind such a subnet.

### Acceptance Criteria
No Azure resources have publicly accessible endpoints - all require credentials to access.

**Comment by emmastephenson** [comment]
@nickclyde do you mind checking this ticket to make sure it adequately captures the work you're doing? TIA!

**Comment by nickclyde** [comment]
This covers the relevant details Emma! The only other sticky issue is that running terraform on GitHubs runners outside the vnet is tricky. I'm still researching solutions to this, hopefully I can just whitelist the runner IP, otherwise the ticket might need to grow in scope, ie using a self-hosted runner that we spin up inside the vnet.

**Comment by emmastephenson** [comment]
Going to bring this up on the Microsoft call 3/14.

**Comment by DanPaseltiner** [comment]
@nickclyde could you please close and link to the ticket with our alternate solution.
