### ISSUE TITLE
Stand up Postgres DB in phdi-playground for TEFCA Connector

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#2226]
We need a Postgres server for likely several databases in the future, but immediately we need a database to persist custom query templates created by our users. Therefore we need to stand up a Postgres DB in the AWS environment owned by Skylight that the `phdi-playground` repository currently deploys to.

Acceptance Criteria

- We can start with the smallest instance AWS RDS instance e.g. t2-micro
- The TEFCA Viewer is the only building block that will need DB access
- The DB should not be accessible from the public internet
- DB credentials can be provided to the TEFCA Viewer as environment variables
- The scope of this ticket does not include implementing a database schema or migrations
- Ultimately we should a Postgres RDS server with one database called `query-templates` (name might need some work)

**Comment by marycrawford** [comment]
@DanPaseltiner - I updated the instance from `db.t2.micro` to `db.t3.micro` since `db.t2` is being phased out and Amazon is no longer going to support it past December 31, 2024.  See Amazon [doc](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html) and screenshot. <img width="1327" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejBLQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e0171e957cea6ca03999040dd09295302343c48/Screenshot%202024-07-24%20at%2010.57.22%E2%80%AFPM.png" alt="Screenshot 2024-07-24 at 10.57.22 PM.png" />

**Comment by marycrawford** [comment]
Secrets Manager is not part of this ticket.  A future ticket will be created to update the architecture.  Right now, we are using the [random_string resource](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/string) and will triple check to see what special character limits for Postgres and apply it to the code.
