### ISSUE TITLE
Re-run Lyme eCR from Tennessee after bug fix

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#2382]
## What needs to be done

TN shared a Lyme eCR with us, and wanted to know how it would display in the eCR Viewer. Unfortunately, #2350 means we're not correctly showing any of the active problems in the eCR Viewer. We need to verify that the bug fix actually fixed the problem for this eCR.

## Why it needs to be done

TN received this eCR and in their current setup, seems that they couldn't discern why it was triggered for Lyme. This is a good test case for our "relevant condition information" section.

"Active Problems" for this eCR were showing up in NBS, but they weren't showing up within the default viewer. TN wants to see what our viewer does for active problems in particular, so they can give appropriate guidance to their epis.

## Acceptance Criteria

- [x] The [TN Lyme eCR](https://drive.google.com/drive/folders/1EIKkbkzAgP96vSeLwzT1VxF8Hqp48XQR?usp=drive_link) has been re-run through the pipeline
- [x] Screenshots taken and shared with Emma
- [ ] If information not being correctly converted/shown, investigate and open a new ticket to resolve

**Comment by angelathe** [comment]
@emmastephenson Screenshot attached below! Active problems are now displayed (except for one which isn't displayed because there was no display name associated with it, just the ICD code. Do you think this a separate bug?)

![localhost_3000_view-data_id=f5058aff-093d-4d49-ac9f-40824c71cd04](https://github.com/user-attachments/assets/9bfe85e2-77ee-4e6d-a084-80e970b07e7c)

FYI, in Active Problems, Onset Age should show _No data_, instead of `57` (this bug has already been reported).

**Comment by emmastephenson** [comment]
@angelathe thank you so much! I'll ask our contact in TN about the ICD code-only problem, I'm curious what the current behavior is there and if we should match it. Will send this over to TN this afternoon! ✅
