### ISSUE TITLE
Improve Orchestration's error messages

### ISSUE THREAD

**Issue by BobanL** [CDCgov/phdi#2467]
## What needs to be done

_Provide a summary of the task that needs to be completed_
- Orchestration provides unhelpful error messages to user.
  - Often times it's just `Internal Server Error` without any additional reason for error

## Why it needs to be done

_Describe the importance or impact of completing this task_
- Improve error handling on orchestration to at least include the service that is failing and the message that is included.

## Acceptance Criteria

_List out all expected functionality/requirements_

- Orchestration error message contains 
  - the service that failed
  - the error message that service returned (without any pii) 

## Technical Notes

_Owned by eng team - write out any important technical considerations such as: architecture plan/notes, data dependencies, testing plan, etc. Also link any tickets that are dependent on or related to this task_

- 

## Additional context

[OPTIONAL, delete if not needed] 
_Include any additional context or information here that doesn't fit into other parts of the template_

**Comment by rin-skylight** [comment]
Note of caution RE: security. Rather than adding detail to the message returned to the user, consider making backend logging more robust, with a switch to enable verbose messages in debug mode only. Relaying too much information in a user-facing error message can give malicious actors more information about a vulnerability. Totally on board with why we need more info...we just need to balance it appropriately. 😁

**Comment by emmastephenson** [comment]
Ask here is only to forward existing messages from underlying services to the orchestration service. If we need to add better logging to other services, that should become a separate ticket.
