### ISSUE TITLE
BUG: Lab performing organization names are incomplete

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2727]
## Description

In the example eCR below, the lab performing organization names are incomplete. Each displays only the initial part, "Stonecrest Medical Center -," without the full name. This is confusing, as all lab entries appear identical with "Stonecrest Medical Center -" but should instead show the full names, such as "Stonecrest Medical Center - POC" or "Stonecrest Medical Center - NETCI," to distinguish the different organizations.

## Steps to reproduce

Example eCR:
`TN_sample eCR2`: [Lab Performer names are not complete](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724877664765269)

## Expected Result

For each performing organization in the eCR, the "Lab Results from" line should display the full name, including any specific identifiers (e.g., "Stonecrest Medical Center - POC" or "Stonecrest Medical Center - NETCI"), to differentiate between the labs performed by different organizations.

## Actual result

Example from `TN_sample eCR2`:
<img width="1934" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzR5Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c46093daeadf75468595e1384e967ff656290549/image.png" alt="image.png" />

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [x] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

N/A

**Comment by BobanL** [comment]
The reason why this occurs is because the NETCI portion is because the [word is being truncated](https://github.com/CDCgov/phdi/blob/76e0e7d015051ed3cf75d44bb8b77e002fd64c22/containers/ecr-viewer/src/app/view-data/components/LabInfo.tsx#L44) and the [default limit is 30 characters](https://github.com/CDCgov/phdi/blob/15a901d71b844bfeb23d6312b0a1b4697794b12a/containers/ecr-viewer/src/app/services/formatService.tsx#L472). Do we think it should be longer than 30 characters here? 


Another option is that we could remove the trailing dash to make it not look out of place?
