### ISSUE TITLE
Set up our own FHIR server to serve requests for our fake patient in demo / integration tests

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/phdi#2758]
In the work for [our super-sick patient](https://github.com/CDCgov/dibbs-query-connector/pull/4), we ran into some issues that we think have to do with the reliability of Public HAPI. We might want to set up our own FHIR server for demo / test use to have more control over how quickly we can access these things over an API call.

**Comment by robertandremitchell** [comment]
As part of this work, we will likely want to also address the ability in demo-mode to click ahead on the SearchForm page without filling out specific fields. Right now, with the public server, clicking nothing advances.

Rather than address it as a separate ticket, I figured it made sense to fold that mini-bug into this work, since we will need to update that step anyway.
