### ISSUE TITLE
Implement Record Linkage API endpoints

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#320]

**Comment by bamader** [comment]
Currently, we have stubs defined for the record linkage API in our cloud service containers. The scope of this ticket is to get the LAC demo-ed version of the DIBBS algorithm running in a containerized service, which will consist of two parts:
1. create a "default algorithm schema" used to load--server-side--the function dictionaries and parameters needed to make the algorithm run
2. complete the "link record" stub in the API so that a single incoming record can be linked against an MPI, with the results returned to the user

**Acceptance Criteria:**
- a dibbs_default.json configuration file is created within the linkage container (see other containers for examples of these schema structures) that houses the parameters and function dictionaries that currently run the linkage algorithm (i.e. first pass, block on this field, match these columns using fuzzy logic, etc.)
- a function is created in the container's main app file that loads an algorithm configuration file and appropriately decomposes it into the pieces needed to make the algorithm work (e.g. for pass N, the blocking fields are A,B,C, the columns that will be exactly matched are X and Y, and the column that will be fuzzy matched is Z)
- the post endpoint stub in the linkage container is fleshed out to receive a single incoming record and run the "dibbs default" algorithm on it--use the previously defined configuration loading function and default json algorithm file to perform a run of the linkage algorithm, including blocking on appropriate fields / retrieving records from the MPI, using cluster-based linking on the returned results based on the algorithm parameters, creating/modifying Person-table information based on the linkage results, then updating the given record and sending it back to the user
