### ISSUE TITLE
SPIKE: Metrics tracking in Kubernetes

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#708]
## Action Requested
Research metrics in Azure Kubernetes Service.

_As a PIPELINE USER, I want to see metrics for my containerized services 
SO THAT I can gauge their performance and take necessary action._

## Acceptance Criteria
We have a plan for implementing any changes required to track metrics for the containers (Terraform resources, Kubernetes resources, etc.)

_GIVEN a container 
WHEN deployed to Azure Kubernetes Services 
THEN I can see performance metrics for that container. (Requests per minute, CPU usage, failed responses, etc)_

## Background & Context
When running the services in ACA, the metrics are fairly easy to find for each resource. So far they're not as obvious in ACA, since most of the metrics in that tab relate to the overall performance of the service instead of the performance of specific pods.

## Additional Information
There are two additional considerations to keep in mind here:
1. How will the move to K8s impact our alerting service? Will we need to make any adjustments there?
2. How will the switch to K8s impact LAC? Are they using any alerts that we'll need to migrate?

**Comment by gordonfarrell** [comment]
Summary of this spike:

I spent most of this spike exploring Prometheus as a metrics solution for K8s. It's generally accepted as the standard/most common and most documented open source K8s monitoring tool. What I found was that it was fairly obtuse to try and implement and basically TOO customizable. Rather than working right out of the box it needs a large amount of babying and setup. On top of that, to get maximum benefit it would need a storage solution and possibly an additional data visualization product on top (e.g. Grafana) of it to achieve max usefulness. Azure's monitoring solutions for K8s seem significantly easier to implement and start running with.

One of the original reason we were exploring K8s in general was to try and make our system cloud agnostic, but as recent developments indicate we'll be living in an Azure world for the foreseeable future, an AZ based solution isn't a big problem.

In a word, after digging into Prometheus and chatting with Emma after her work with AM, I suggest we not use Prom and go with the azure solution for the time being. Let me know if anyone has questions!
