### ISSUE TITLE
Add cleaning of DateTimes to HL7 batch cleaning function

### ISSUE THREAD

**Issue by nickclyde** [CDCgov/phdi#928]
After the discovery of this issue with processing ELRs from LAC:

```
The errors all seem to have to do with incorrectly formatted date strings:
The format of Date or DateTime is invalid: 20230820185501-080000000.

This has 5 extra zeroes after a valid datetime string. We inspected a failed ELR message, and it contained a number of correctly formatted datetimes alongside this incorrect one with five extra zeroes.
```

We've decided to add a simple cleaning function to fix the issue. We should match strings in the format (14digits-9digits) and strip off the last 5 digits to get a proper datetime. The place we should do this is in the [_clean_hl7_batch](https://github.com/CDCgov/phdi/blob/main/phdi/harmonization/hl7.py#L272) function, which gets called by the ReadSourceData function app on initial message ingestion.

**Comment by robertmitchellv** [comment]
the weird thing about this is that the following function (based on my read) _should_ work for this because it is using a regex to extract the time zone offset and then truncate:

https://github.com/CDCgov/phdi/blob/405ba57fc1b4996b67d4af30b7025684f05e5cac/phdi/harmonization/hl7.py#L230

i'm going to try and spin things up locally and test some more to figure out why this isn't working as expected
