### ISSUE TITLE
SPIKE: FHIR Libraries for eCR Viewer

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#930]
## Action Requested
Investigate options for FHIR object libraries to use in the eCR viewer.

## Acceptance Criteria
We've made a decision about which FHIR library to use in order to extract data for the eCR viewer (without re-inventing the wheel of FHIR paths.)

## Background & Context
For the eCR viewer, we're going to need to flexibly extract data from FHIR bundles that have passed through the DIBBs pipeline. Maintaining a huge configuration mapping of `exact fhir path`: `field we need to display` would be untenable, so we should use existing FHIR libraries to retrieve this data. (e.g, why develop the mapping for `Patient/name/family` : `patient_last_name` if we can just call `bundle.getPatientLastName`)

We're not completely wedded to a language here either - Python, JavaScript, or even Java are all on the table. JavaScript would be preferable, but if that's not possible then we should pick whichever library is best out of the other languages.

## Additional Information
A couple of resources:

* [HL7 keeps a list of all FHIR-related libraries across languages](https://confluence.hl7.org/display/FHIR/Open+Source+Implementations)
* [DefinitelyTyped includes a FHIR mapping](https://www.npmjs.com/package/@types/fhir)
* [FHIR.js exists](https://github.com/FHIR/fhir.js/)
    * Unclear if this library is for FHIR servers, FHIR queries, or FHIR objects 
* There's always the [HAPI FHIR library](https://github.com/hapifhir/hapi-fhir), but that would require us to spin up a Java service
    * Depending on how good the other library options are, this could be worth it

**Comment by BobanL** [comment]
It appears that there are no FHIR libraries that support functionality to retrieve specific information from a FHIR Bundle, like `bundle.getPatientLastName()`. 
The recommend approach at this time is to use is a combination of [`@types/fhir`](https://www.npmjs.com/package/@types/fhir) and [fhirpath.js](https://github.com/HL7/fhirpath.js) since it is light weight and well maintained. We also have the option to use [`@medplum/core`](https://github.com/medplum/medplum/tree/main/packages/core) and [`@medplum/fhirtypes`](https://github.com/medplum/medplum/tree/main/packages/fhirtypes) as this will provide the same functionality as above and additional functionality to help format some resources like HumanName and Address to a String, but also includes a lot of unneeded functionality like a Fhir client. 


Here are some of my rough notes for the other libraries I looked at:
1. [FHIR.JS](https://github.com/lantanagroup/FHIR.js)
    * Serialize between XML & JSON, validates FHIR resources, and can evaluate FHIR path
5. [`@types/fhir`](https://www.npmjs.com/package/@types/fhir)
    * Pretty much the same as Med-Plum’s types
6. [Java - Hapi FHIR](https://hapifhir.io/)
    * Provides types, server and client capabilities, and other java/spring libraries (spring boot starter, JPA, etc) .
7. [C# - Firely](https://github.com/FirelyTeam/firely-net-sdk)
    * Their examples loop through entries to look for data in the bundle 
2. [Fhir-React](https://github.com/1uphealth/fhir-react)
    * Converts FHIR json into react component. 
        * Uses Lodash _.get to get different elements and walk through the bundle
            * https://github.com/1uphealth/fhir-react/blob/127811b4d5a8de17fb6dfae21331d1fec97d848f/src/components/resources/Bundle/Bundle.js#L3
            * https://github.com/1uphealth/fhir-react/blob/9b583a2fddb0ac586a39c40e711f9836dbf6d4a7/src/components/resources/Patient/Patient.js#L42
            * No real difference then using FhirPath
        * [Storybook example](http://storybook-fhir-react-lib.s3-website-us-east-1.amazonaws.com/dev/main?path=/story/bundle--example-3-of-r-4) 
3. [React - FhirUI](https://github.com/healthintellect/fhir-ui)
    * Doesn’t handle bundles, only specific resources.
4. [Med-Plum](https://github.com/medplum/medplum/tree/main)
    * Library contains a lot of FHIR packages. 
    * FHIRTypes has a bundle type, but entries is just an array of entry types. It’s not easy to get a specific resource.
    * Their react library takes small pieces like HumanName and formats it with their core package
    * [Core](https://github.com/medplum/medplum/tree/1bbb4856f5ed76021f2b0d64de5cc1f5620fa93b/packages/core) provides [formatting](https://github.com/medplum/medplum/blob/1bbb4856f5ed76021f2b0d64de5cc1f5620fa93b/packages/core/src/format.ts#L70) for many FHIR types like address, and name.  
        * Can evaluate FHIR path
        * Can also validate FHIR, provides websockets and a FHIR client.
