### ISSUE TITLE
Create configuration page for users to select/deselection fields 

### ISSUE THREAD

**Issue by jankimo** [CDCgov/phdi#970]

**Comment by robertandremitchell** [comment]
My initial thought is to make this page more dynamic: https://github.com/CDCgov/phdi-playground/blob/main/front-end/app/export/page.tsx

I think it should be possible to make the page formatted and dynamic based on the json with metadata. Perhaps for those with an array, with labs, for example, we would just note the number of labs that would be downloaded, rather than sifting through all labs.

with the checkbox here: https://designsystem.digital.gov/components/checkbox/. Everything would be pre-selected, and we would only

**Comment by robertandremitchell** [comment]
Will actually need to update these, as well: 
https://github.com/CDCgov/phdi-playground/blob/main/front-end/components/ECRTable/ECRTable.tsx

So that would change the display to a checkbox system, but then we would need to still change the download in the export step to update what gets downloaded.

**Comment by robertandremitchell** [comment]
https://github.com/CDCgov/phdi-playground/blob/main/front-end/components/ECRTable/ECRTable.tsx#L6 I wonder if this could be replaced with reading in https://github.com/CDCgov/phdi/blob/main/containers/message-parser/app/default_schemas/ecr.json.
