### ISSUE TITLE
Add button to download full CSV 

### ISSUE THREAD

**Issue by jankimo** [CDCgov/phdi#971]

**Comment by robertandremitchell** [comment]
@jankimo two proposed CSV layouts to discuss with Ryan today. Uploading as a txt file because ZenHub doesn't support CSV apparently (?). Anyway, this is what I was toying around with to eventually add. There is also a third option of essentially a "hybrid" where one sheet is "wide" with all the patient level info, while the lab and active problem and any other array data is a separate sheet within an Excel notebook.

[long_example.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFZMQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce0d24d485ffcbb0f0cbf6713c09af76c7b23f57/long_example.txt)

**Comment by robertandremitchell** [comment]
@jankimo I defer to you on whether to close or just leave icebox'd for now.

**Comment by jankimo** [comment]
I'll close since this is a temp team, when eCR viewer can be used we can open the relevant ticket on that board.
